Repository mpdavis/python-jose, pull requests merged in 2019-12, with the labels that each got.

#157 Bump version to 3.1.0
  .travis.yml
  jose/__init__.py
  tox.ini
Labels: version

#159 Last 3.1.0 tweaks
  .travis.yml
  CHANGELOG.md
  CHANGELOG.rst
  setup.py
Labels: version

#140 remove unused JWTSignatureError class
  jose/exceptions.py
Labels: help wanted

#165 Json encodeable jwk dict
  CHANGELOG.md
  CHANGELOG.rst
  jose/backends/cryptography_backend.py
  jose/backends/ecdsa_backend.py
  jose/backends/pycrypto_backend.py
  jose/backends/rsa_backend.py
  jose/jwk.py
  tests/algorithms/test_EC.py
  tests/algorithms/test_HMAC.py
  tests/algorithms/test_RSA.py
Labels: bug

#167 Require setuptools>=39.2.0
  setup.cfg
  setup.py
Labels: bug

#168 Just emit a warning when verifying with a private key
  .travis.yml
  jose/backends/pycrypto_backend.py
  jose/backends/rsa_backend.py
  jose/utils.py
  pytest.ini
  setup.py
  tests/test_jws.py
Labels: enhancement
